version: '3.1'
services:
  dbpostgresql:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=mydb
  app:
    container_name: app-springboot
    image: app-springboot-postgresql
    build: ./
    ports:
      - 8282:8282
    depends_on:
      - dbpostgresql
    environment:
      - SERVER_PORT=8282